# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Abhishek Shandilya
email: abhishek.sandy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Learn more about Abhishek Shandilya by going through his projects,
  work experience and blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://abhishandy.github.io" # the base hostname & protocol for your site
twitter_username: abhishandy
github_username:  abhishandy

# Build settings
markdown: kramdown
